# Generated by Django 3.1.4 on 2020-12-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201208_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='datecompleted',
        ),
    ]
