# Generated by Django 3.1.4 on 2020-12-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_query_datecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='memo',
            new_name='query',
        ),
        migrations.AlterField(
            model_name='query',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
