# Generated by Django 3.1.4 on 2020-12-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20201208_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
